### ISSUE TITLE
Request: Add video sharpening support

### ISSUE THREAD

**Issue by myghi63** [WiVRn/WiVRn#163]
Hello, I hope you're having a good day.

I'm a new user of WiVRn and I noticed that this app lacks support of color correction, specially video sharpening.
Using the native resolution of my headset (2160x2160) the game looks like it's running on a way lower resolution if compared to any other streamer that supports video sharpening. 

It would be quite important to implement since it can potentially improve the overall quality of the stream, by compensating the blurriness caused by video encoding / decoding.

Best Regards,
Melany

**Comment by galister** [comment]
Hi Melany,

Don't use the native resolution of your headset, because it doesn't work the same way it does with 2D games on 2D screens.

Once the game is rendered, it is displayed on a flat plane in 3D space, in front of your eyes, using prediction of where your eyes will be by the time the frame has finished rendering. This is then sampled using the actual pose of your eyes at the time of displaying that frame. The images will never line up in a pixel perfect way.

This is also the case with SteamVR and _other streamers_. Most of them (VD, Steam Link) use a higher resolution than the panel res, with the actual resolution being hidden from the user, because they know that those pesky users would try to set it to 1:1 and complain.

With ALVR, it's possible to achieve 1:1, if you set all of these 3 to your native res: 
- Transcoding view resolution (in ALVR)
- Emulated headset view resolution (in ALVR)
- SteamVR resolution scale (in SteamVR)
You'll notice that it's about as equally blurry as WiVRn is. The sharpening filter actually worsens aliasing, so text will likely be harder to read in ALVR.

Try the default values of 1.4 resolution scale in the WiVRn client app and 0.5 foveation scale on the server. These values result in a good balance between quality and performance. Adjust client scale if more detail is needed, and adjust foveation scale if the edges of the screen are too blurry for your taste. On a headset that uses its RGB subpixels properly (Quest series), improvements can be seen even at 2.0 client resolution scale. This is obviously not very GPU friendly, so the usual choice is somewhere between 1.4-1.6

**Comment by myghi63** [comment]
Thanks, I tested it on my setup and it turns out to be working great ^^
The difference in quality is very significant
