### ISSUE TITLE
Warping / Distorted Image after Update to v0.21

### ISSUE THREAD

**Issue by Okabintaro** [WiVRn/WiVRn#165]
I just got the client update of wivrn through the meta store.
Then I updated the server by checking out the tag v0.21 and rebuilding now I am seeing this weird distortion(see video):

https://github.com/user-attachments/assets/27337ada-8ccd-40ff-964c-567219864182

Any idea what could be wrong? Everything was working

 fine with v0.20.
I am using a quest 3, and built the server on arch. 
Also attached the logfile os wivrn and wlx-overlay, but I couldn't see anything weird there: [wivrn.log](https://github.com/user-attachments/files/17611672/wivrn.log)

**Comment by xytovl** [comment]
As discussed in discord, bissecting the commit could help.

There are some other elements to investigate:
does scale (client and server) affect the issue?
does it happen with an entirely empty server configuration file?
can you dump the server-side video with `WIVRN_DUMP_VIDEO=/path/to/file` and see if it has glitches? It should be distorted due to foveated encoding, and show 2 images side-by-side.

**Comment by Meumeu** [comment]
Fixed in v0.21.1
