### ISSUE TITLE
HMD Pairing Workflow Updates

### ISSUE THREAD

**Issue by damaestro** [WiVRn/WiVRn#191]
While testing out the pairing using https://github.com/WiVRn/WiVRn/commit/bab3a2395352dfcc24ff489545af2e2df1c5057c , there are a few things that seem to be needing an update:

* If a HMD has been paired before and the server is put into pairing mode again, the client doesn't attempt to renegotiate. The workaround is to uninstall the HMD and install it again.

Recommendation: a) if the server is in pairing mode, renegotiate and/or b) add menu item to clear pairing code for a given server in the HMD

* Incorrect pairing code doesn't give any user feedback. The connection eventually times out and the server logs "Client connection failed: Socket shutdown". Clicking "close" and trying to connect again does attempt another pairing. 

Recommendation: short circuit earlier and show the user there was an issue with the pairing code and to enter it again.

* When pairing is successful, measured by audio going to the HMD and showing "connection ready" the server logs a constantly connecting/disconnected client:

```
[...]
 INFO [client_loop] Client disconnected.
 INFO [client_loop] Client 66 connected
 INFO [client_loop] Client disconnected.
 INFO [client_loop] Client 67 connected
 INFO [client_loop] Client disconnected.
 INFO [client_loop] Client 68 connected
 INFO [client_loop] Client disconnected.
 INFO [client_loop] Client 69 connected
 INFO [client_loop] Client disconnected.
 INFO [client_loop] Client 70 connected
 INFO [client_loop] Client disconnected.
 INFO [client_loop] Client 71 connected
[...]
```

**Comment by xytovl** [comment]
pairing mode is used to add headsets, we don't have an UI to remove paired headsets yet so already paired ones just connect without requiring a new PIN.

The incorrect PIN is an issue we are trying to fix, but this is not obvious without allowing brute-forcing of the PIN.

Is the client connect/disconnect loop when using envision? It can be caused by a loop trying to use an old libmonado due to https://gitlab.com/gabmus/envision/-/issues/146

**Comment by damaestro** [comment]
Yes, the `client_loop` is when using envision.

**Comment by damaestro** [comment]
> The incorrect PIN is an issue we are trying to fix, but this is not obvious without allowing brute-forcing of the PIN.

Keep track of clients with failed attempts. If number of failed attempts is over a reasonable amount, block the client until the server is restarted or the server leaves and re-enters paring mode. Log that a client is being ignored due to failed authentication.

**Comment by Meumeu** [comment]
> Keep track of clients with failed attempts. If number of failed attempts is over a reasonable amount, block the client until the server is restarted or the server leaves and re-enters paring mode. Log that a client is being ignored due to failed authentication.

We were already planning on doing something like that, except globally instead of per-client because it's easy to change the IP address for every attempt. The harder part is to do it in a way that doesn't allow a MITM attack to allow the attacker to connect, which means we can't just send the PIN to check it, or even a hash or an encrypted version of the PIN.

**Comment by Meumeu** [comment]
I'm probably overthinking it, but I'd rather do it right even if I don't think a lot of people will bother writing an exploit for WiVRn.

**Comment by damaestro** [comment]
It's worth doing right.

**Comment by Meumeu** [comment]
I've put a first version in [feat/check-pin](https://github.com/WiVRn/WiVRn/tree/feat/check-pin), there's still an internal compiler error in the flatpak build.

**Comment by damaestro** [comment]
@Meumeu works great.
