### ISSUE TITLE
[Feature Request]: Sound forwarding.

### ISSUE THREAD

**Issue by Oglo12** [WiVRn/WiVRn#211]
### Feature description

The ability to play sound on the headset.

### Reason for the feature

It is really annoying to have to hear the sound from my laptop speakers as opposed to my actual headset.

**Comment by galister** [comment]
To forward your PC audio to the headset:
- Have the headset connected
- Open PulseAudio Volume Control aka `pavucontrol`
- Select the `Output Devices` tab
- From the `Show` drop-down (on the bottom), select `All Output Devices`
- Click the circled check mark icon next to WiVRn in order to make it the default while it's connected

Your system will remember this setting and switch to it automatically unless you're somehow actively overriding it.

As for microphone, simply select the WiVRn microphone in the game as the desired microphone.

**Comment by Oglo12** [comment]
Ah, okay, thank you!
